### ISSUE TITLE
一个功能建议,可以根据分辨率来添加720P 1080P 4K吗?

### ISSUE THREAD

**Issue by saz369** [Hermit10/AVDCx#23]
请问能够添加一个小功能,根据分辨率来命名的时候添加 720P 1080P 4K, 或者做成风格,标签吗?

**Comment by Hermit10** [comment]
这个分辨率要读取视频才能获取，估计速度有影响。

**Comment by Huaneg** [comment]
但是如果文件名里有“4K”的话，是不是能直接在海报上添加一个 4K 的标签？

**Comment by saz369** [comment]
可以做成选项.我个人觉得慢一点没有关系

**Comment by saz369** [comment]
> 但是如果文件名里有“4K”的话，是不是能直接在海报上添加一个 4K 的标签？

这个emby里面有功能可以做到你下载一个叫coverart的

**Comment by Hermit10** [comment]
已增加字段：definition
表示视频清晰度，包括8K/4K/1440P/1080P/960P/720P/540P/360P/144P
版本：20210908
