### ISSUE TITLE
又一个 javlibrary 的bug

### ISSUE THREAD

**Issue by tanlicheng703283** [Hermit10/AVDCx#34]
只要在javlibrary搜索页（用浏览器）有出现2个结果 就会失败 如下 其他：SSNI-794 SSNI-795 都是一样
🙈 [Movie] I:\SSNI-994.mp4
 🚘 [Number] SSNI-994
 🌐 [website] javlibrary[jp]
 🟠 Data failed!
   ****** Debug Info ******
   >>> javlibrary-开始使用javlibrary 进行刮削
   >>> javlibrary-生成搜索页地址: https://www.javlibrary.com/ja/vl_searchbyid.php?keyword=SSNI-994
   >>> javlibrary-搜索结果页：未匹配到番号！
 🔴 [Error] javlibrary-搜索结果页：未匹配到番号

**Comment by Hermit10** [comment]
收到

**Comment by Hermit10** [comment]
已修复，更新版本20210906
