### ISSUE TITLE
屏蔽中文字符文件

### ISSUE THREAD

**Issue by ShmilyChen** [Hermit10/AVDCx#35]
很多磁力下载下来会附带很多广告的mp4文件，这些文件一般都是中文命名，希望可以加一个开关，标题包含中文自动跳过不刮削，经常刮削的时候时间被浪费在这

**Comment by ShmilyChen** [comment]
> 一个是下载的时候可以选择不下载这些文件...第二个是可以手动删掉...还有人的文件名命名规则里面包含了标题的...按照这个规则是不是也会被忽略掉...最好还是自己动动手吧...

所以我提了是开关，默认取消勾选

**Comment by pikachullk** [comment]
加个开关倒是ok的～主要是怎么实现屏蔽中文字符？感觉删掉那些文件或者干脆不下广告文件不好像更直接点…

**Comment by ShmilyChen** [comment]
> 觉删掉那些文件或者干脆不下广告文件不好像更直接点…

百度的`https://www.cnblogs.com/xiao987334176/p/11239982.html`
```
def is_chinese(string):
    """
    检查整个字符串是否包含中文
    :param string: 需要检查的字符串
    :return: bool
    """
    for ch in string:
        if u'\u4e00' <= ch <= u'\u9fff':
            return True

    return False

ret1 = is_chinese("刘亦菲")
print(ret1) #True

ret2 = is_chinese("123")
print(ret2)#False
```

**Comment by pikachullk** [comment]
直接PR嘛....

**Comment by Hermit10** [comment]
通过中文过滤会有误伤，感觉用文件大小更好些。
再或者指定字符过滤。

**Comment by Hermit10** [comment]
已更新过滤小文件功能，版本20210907
