### ISSUE TITLE
功能建议，封面图片裁剪

### ISSUE THREAD

**Issue by Tough-JK** [Hermit10/AVDCx#37]
在avdcx的软件主界面中能不能加一个，添加打开以前刮好的片，然后可以预览封面图和缩略图，方便对以前刮削的电影，电影封面有偏差的进行裁剪，软件已经很好用了，如果代码量大，大佬看看就好0.0

**Comment by Tough-JK** [comment]
还有一个问题，封面裁剪在裁剪的时候所使用的图片是thumb而不是fanart。
会出现一个问题，如果thumb上有水印，在剪的过程中又再次勾选了水印，会出现水印重叠。

**Comment by Hermit10** [comment]
可以加，以后有时间可以加上。

**Comment by Hermit10** [comment]
已修复，更新版本20210906
