### ISSUE TITLE
中文字幕视频无法识别出来，也不能改名

### ISSUE THREAD

**Issue by liruishengus** [Hermit10/AVDCx#38]
3/34 (8.82%) round(1) AARM-008-C.mp4
================================================================================
 🙈 [Movie] Y:\AARM-008-C\AARM-008-C.mp4
 🚘 [Number] AARM-008
 🌐 [website] iqqtv[jp] -> iqqtv[cn] -> javdb
 🟢 Data done!
 ⏱ YouDao Translation will request after 5 seconds!
 🟢 YouDao Translation done!
    title     : 乳头自慰骚疼股间夹住东西伸腿高潮的女子
    actor     : 吉良薫,吉乃桃果,成田䌷,萌木こはる,椎名めろ
    outline   : 即使是比别人敏感一倍的女孩子，也很难只靠乳头手淫来喂奶。有一天，乳头手淫导致下半身疼痛的女孩把床上的枕头夹在双腿上。于是…给乳头的刺激传达身体的芯，夹在股间的物体好像舒服地把脚别针的ma〇〇给给了......（略）
    tag       : 巨乳,自慰,穿衣幹砲,微乳
    release   : 2021-08-19
    year      : 2021
    runtime   : 105
    score     : 3.5
    director  : ハム王子
    publisher : アロマ企画
    studio    : アロマ企画
    website   : https://iqqtv.cloud/cn/player.php?uuid=otxahztY9B
    mosaic    : 有码
 🔴 The success folder already has a same name file!
   >>> The current path is 'Y:\JAV_output\AARM-008-乳头自慰骚疼股间夹住东西伸腿高潮的女子-2021-08-19\AARM-008.mp4'
 🔴 [Error] The success folder already has a same name file! 
   >>> The success path 'Y:\JAV_output\AARM-008-乳头自慰骚疼股间夹住东西伸腿高潮的女子-2021-08-19\AARM-008.mp4' already exists 
   >>> The file will not be moved to the success folder!
   >>> Move file to the failed folder! 
   >>> The new path is 'Y:\failed\AARM-008-C.mp4'

已经在<目录和文件设置>里面设置了<中文字幕字符样式>“-C”，还是不行...

**Comment by theturtle626** [comment]
錯誤訊息 : 已經有相同名稱,  所以不再寫入

但一個是 AARM-008.mp4, 一個是 AARM-008-C.mp4, 應該視為不同名稱

**Comment by liruishengus** [comment]
> 錯誤訊息 : 已經有相同名稱, 所以不再寫入
> 
> 但一個是 AARM-008.mp4, 一個是 AARM-008-C.mp4, 應該視為不同名稱

对的，软件应该会把AARM-008-C.mp4视为一个新文件拷贝到AARM-008文件夹下面，这个文件夹应该存在两个文件才对...但是软件报错有重复文件了，也就是改版程序的中文字符识别出错了无法识别-C的文件......原版程序并没有这个问题...望修复

**Comment by Hermit10** [comment]
截图设置页面或者上传config.ini文件
猜测是你设置的目录命名规则里没有加（中文字幕）这个字段。

**Comment by liruishengus** [comment]
> 截图设置页面或者上传config.ini文件
> 猜测是你设置的目录命名规则里没有加（中文字幕）这个字段。

`[modified_time]
modified_time = 2021-09-02 09:31:23

[common]
main_mode = 1
main_like = 1
success_file_move = 1
failed_file_move = 1
success_file_rename = 1
soft_link = 0
show_poster = 1
translate_language = zh_cn
# zh_cn or zh_tw or ja
translate_content = title,outline,actor,tag
translate_by = youdao
# youdao or deepl
deepl_key = 
website = all
# all or iqqtv or javbus or javdb or jav321 or dmm or avsox or xcity or mgstage or fc2 or fc2club or fc2hub or airav or javlibrary
series_as_set = 1

[proxy]
type = no
proxy = 127.0.0.1:7890
timeout = 10
retry = 3
# type: no, http, socks5

[Cookies]
javdb = 
# cookies存在有效期，记得更新

[Name_Rule]
folder_name = number-title-release
naming_media = number-title
naming_file = number
del_actor_name = 1
# 命名字段有：title, actor, number, studio, publisher, year, mosaic, runtime, director, release, series

[update]
update_check = 1

[log]
save_log = 1

[media]
media_path = Y:\
success_output_folder = JAV_output
failed_output_folder = failed
extrafanart_folder = 
cnword_char = -C,中文,字幕
cnword_style = -C
media_type = .mp4|.avi|.rmvb|.wmv|.mov|.mkv|.flv|.ts|.webm|.iso|.mpg
sub_type = .smi|.srt|.idx|.sub|.sup|.psb|.ssa|.ass|.txt|.usf|.xss|.ssf|.rt|.lrc|.sbv|.vtt|.ttml

[escape]
folders = JAV_output,examples,failed
string = 1080p,720p,22-sht.me,-HD

[debug_mode]
switch = 1

[emby]
emby_url = 192.168.5.191:8096
api_key = cb83900340b447fab785cb628a99c3da

[mark]
poster_mark = 1
thumb_mark = 1
mark_size = 1
mark_type = SUB,LEAK,UNCENSORED
mark_pos = top_left
# mark_size : range 1-5
# mark_type : sub, leak, uncensored
# mark_pos  : bottom_right or bottom_left or top_right or top_left

[uncensored]
uncensored_prefix = BT|CT|EMP|CCDV|CWP|CWPBD|DSAM|DRC|DRG|GACHI|heydouga|JAV|LAF|LAFBD|HEYZO|KTG|KP|KG|LLDV|MCDV|MKD|MKBD|MMDV|NIP|PB|PT|QE|RED|RHJ|S2M|SKY|SKYHD|SMD|SSDV|SSKP|TRG|TS|xxx-av|YKB|heydouga|1pon|Carib
uncensored_poster = 1
# 0 : official, 1 : cut

[file_download]
old_poster = 0
old_thumb = 0
old_fanart = 0
old_extrafanart = 0
old_extrafanart_copy = 0
old_nfo = 0
poster = 1
thumb = 1
fanart = 1
extrafanart = 0
extrafanart_copy = 0
nfo = 1
`

麻烦大侠帮忙看看了，感谢~

**Comment by liruishengus** [comment]
我删除了config.ini之后，用软件自己重新生成的配置文件后，发现默认的配置文件有点问题，比如文件命名方式，中文字幕会变成空白的，排除文件夹failed没有了，和原版不一样了...

**Comment by Hermit10** [comment]
改成这样：
naming_file = number中文字幕

**Comment by Hermit10** [comment]
> 我删除了config.ini之后，用软件自己重新生成的配置文件后，发现默认的配置文件有点问题，比如文件命名方式，中文字幕会变成空白的，排除文件夹failed没有了，和原版不一样了...

没看懂，截图看看？

**Comment by liruishengus** [comment]
我上传不到图片...

**Comment by Hermit10** [comment]
复制，粘贴就可以。

**Comment by Hermit10** [comment]
已去掉中文字幕字段，改为手动勾选，更新版本20210906
