### ISSUE TITLE
希望恢复中文字幕字段

### ISSUE THREAD

**Issue by xingkb** [Hermit10/AVDCx#40]
需要在nfo标题中输出是否中文，以便下载站时识别自己是否已经下载了中文版本

**Comment by Hermit10** [comment]
不喜欢水印？

**Comment by Hermit10** [comment]
下个版本加上了。

**Comment by xingkb** [comment]
我写了油猴 通过emby的API  通过番号匹配搜索替换了视频下载站的标题，根据标题来确认是否需要补下字幕

**Comment by Hermit10** [comment]
中文字段已更新，20210911😂
