### ISSUE TITLE
DeepL翻译端口出错

### ISSUE THREAD

**Issue by tiancai63** [Hermit10/AVDCx#41]
我今天在使用ACDCx的时候，有极小部分的视频出现无法翻译的状况，作者可以麻烦看一下是什么状况吗?
（错误提示：本次翻译将跳过！deepl翻译接口返回数据异常2！返回内容：{'message': 'Wrong endpoint. Use https://api-free.deepl.com'}）
我刚刚重新试了下，之前翻译成功的再删除NFO文件后重新收集，还是可以翻译的

log:
1/4 (25.00%) round(6) SSPD-157.mp4
================================================================================
 🙈 [Movie] F:\新建文件夹\JAV_output\SSPD-157.mp4
 🚘 [Number] SSPD-157
 🌐 [website] iqqtv[jp] -> iqqtv[cn] -> javdb -> jav321-> dmm
 🟢 Data done!
    title     : 时隔多年的同学会喝醉的美人妻松下纱容子遇到昔日恩师被强行插入激发了淫荡本性忘我地做到早上
    actor     : 松下纱栄子
    outline   : 在同学会又遇见了以前就喜欢的人。即使已经毕业10年了，老师还是跟那时候一样美艳动人...
    tag       : 中出,AV女优片,巨乳,人妻,戏剧、连续剧,HD高画质,寝取り・寝取られ・ntr,1080P
    release   : 2020-04-07
    year      : 2020
    runtime   : 108
    score     : 4.55
    director  : さだおかさだお
    publisher : アタッカーズ
    studio    : アタッカーズ
    website   : https://iqqtv.cloud/cn/player.php?uuid=traUGxLPga6
    mosaic    : 有码
    definition: 1080P
 🟢 Thumb done!
 🟢 Poster done!
 🟢 Fanart done!
 🟢 Nfo done!
 🟢 Movie not moved! 
   >>> The path is 'F:\新建文件夹\JAV_output\SSPD-157.mp4'

2/4 (50.00%) round(6) DLDSS-027.mp4
================================================================================
 🙈 [Movie] F:\新建文件夹\JAV_output\友田彩也香\DLDSS-027 友田彩也香\DLDSS-027.mp4
 🚘 [Number] DLDSS-027
 🌐 [website] iqqtv[jp] -> javbus -> javdb -> jav321-> dmm
 🟢 Data done!
 🟠 本次翻译将跳过！deepl翻译接口返回数据异常2！返回内容：{'message': 'Wrong endpoint. Use https://api-free.deepl.com'}
 🟠 本次翻译将跳过！deepl翻译接口返回数据异常2！返回内容：{'message': 'Wrong endpoint. Use https://api-free.deepl.com'}
 🟢 DeepL Translation done!
    title     : あなたにだけは知られたくない…ラブラブな笑颜でお姊ちゃんが结婚报告に来たその日、妹の私は义兄になったばかりの男に袭われました。
    actor     : 友田彩也香
    outline   : ある日姊が我が家にやって来た、得体の知れない男を连れて。结婚したと幸せそうだ。男はしかし、私の体を舐め回すような视线を送ってくる、夫の目の前で。その夜から人妻あかりは义兄に缲り返し袭われた...友......（略）
    tag       : 高畫質,中出,戲劇,出軌,已婚婦女,單體作品,1080P
    release   : 2021-09-09
    year      : 2021
    runtime   : 125
    score     : 4.5
    director  : 西郷ショウ
    publisher : DAHLIA
    studio    : DAHLIA
    website   : https://www.javbus.com/DLDSS-027
    mosaic    : 有码
    definition: 1080P
 🟢 Thumb done!
 🟢 Poster done!
 🟢 Fanart done!
 🟢 Nfo done!
 🟢 Movie not moved! 
   >>> The path is 'F:\新建文件夹\JAV_output\友田彩也香\DLDSS-027 友田彩也香\DLDSS-027.mp4'

3/4 (75.00%) round(6) FSDSS-282.mp4
================================================================================
 🙈 [Movie] F:\新建文件夹\JAV_output\天川そら\FSDSS-282 天川そら\FSDSS-282.mp4
 🚘 [Number] FSDSS-282
 🌐 [website] iqqtv[jp] -> javbus -> javdb -> jav321-> dmm
 🟢 Data done!
 🟠 本次翻译将跳过！deepl翻译接口返回数据异常2！返回内容：{'message': 'Wrong endpoint. Use https://api-free.deepl.com'}
 🟠 本次翻译将跳过！deepl翻译接口返回数据异常2！返回内容：{'message': 'Wrong endpoint. Use https://api-free.deepl.com'}
 🟢 DeepL Translation done!
    title     : ささやき上手な天川先生と内绪の校内禁断イクイクSEX
    actor     : 天川そら
    outline   : 绝対にいけない场所、これ以上ない危険なタイミングで、耳元に流れ込むひそひそ诱惑。密着して、ねっとりと、いやらしく…天川先生は常に生徒のチ○ポを狙っているのです。スリル満点の校内交尾なのに、先生の敏......（略）
    tag       : 高畫質,巨乳,連褲襪,學校作品,女教師,單體作品,1080P
    release   : 2021-09-09
    year      : 2021
    runtime   : 120
    score     : 4.63
    director  : とんかつ
    publisher : FALENO star
    studio    : FALENO
    website   : https://www.javbus.com/FSDSS-282
    mosaic    : 有码
    definition: 1080P
 🟢 Thumb done!
 🟢 Poster done!
 🟢 Fanart done!
 🟢 Nfo done!
 🟢 Movie not moved! 
   >>> The path is 'F:\新建文件夹\JAV_output\天川そら\FSDSS-282 天川そら\FSDSS-282.mp4'

4/4 (100.00%) round(6) MIST-347.mp4
================================================================================
 🙈 [Movie] F:\新建文件夹\JAV_output\莲実クレア\MIST-347 莲実クレア\MIST-347.mp4
 🚘 [Number] MIST-347
 🌐 [website] iqqtv[jp] -> javbus -> javdb -> jav321-> dmm
 🟢 Data done!
 🟠 本次翻译将跳过！deepl翻译接口返回数据异常2！返回内容：{'message': 'Wrong endpoint. Use https://api-free.deepl.com'}
 🟠 本次翻译将跳过！deepl翻译接口返回数据异常2！返回内容：{'message': 'Wrong endpoint. Use https://api-free.deepl.com'}
 🟢 DeepL Translation done!
    title     : 危険日直撃！！子作りできるソープランド31
    actor     : 莲実クレア
    outline   : 美しい嬢が危険日のみ出勤するソープには彼女たちを孕ませたい中出し希望者が足繁く通う。子持ち人妻嬢クレアさんが今回接待するのは初来店のお客様。常连になり特别なお客様だけが许される自宅ソープへ招待され......（略）
    tag       : 高畫質,女上位,孕ませ,妓女,單體作品,巨乳,1080P
    release   : 2021-09-09
    year      : 2021
    runtime   : 161
    score     : 5.0
    series    : 危険日直撃！！子作りできるソープランド
    director  : サイタ
    publisher : Mr.michiru
    studio    : Mr.michiru
    website   : https://www.javbus.com/MIST-347
    mosaic    : 有码
    definition: 1080P
 🟢 Thumb done!
 🟢 Poster done!
 🟢 Fanart done!
 🟢 Nfo done!
 🟢 Movie not moved! 
   >>> The path is 'F:\新建文件夹\JAV_output\莲実クレア\MIST-347 莲実クレア\MIST-347.mp4'
================================================================================
 🎉🎉🎉 All finished!!! Total 4 , Success 4 , Failed 0
================================================================================

**Comment by Hermit10** [comment]
失败的番号用以前版本可以翻译吗？

**Comment by tiancai63** [comment]
> 失败的番号用以前版本可以翻译吗？

我刚刚用了2021.08.06的版本测试，还是失败。然后我又重新测试了下今天新出的几个片子，没有一个成功翻译，都是显示同样的错误。我猜测可能之前成功的并不是翻译而是网站翻译好后直接获取的而不是通过DeepL翻译获得的。 

我用的是DeepL API Free免费会员，我猜测免费会员用的端口和付费会员不一样。

**Comment by Hermit10** [comment]
估计你的猜测是对的。调试时，我是用网友给的付费key测试的，没有测试免费会员。

**Comment by tiancai63** [comment]
> 估计你的猜测是对的。调试时，我是用网友给的付费key测试的，没有测试免费会员。

如果方便的话可以加上免费会员的通道吗？

**Comment by Hermit10** [comment]
我没有免费会员，刚看了这个没有开放中国地区。

**Comment by Hermit10** [comment]
你可以用telegram发我（@hermit10）一下你的api，我调试看看。

**Comment by Hermit10** [comment]
已更新，版本20210910
