### ISSUE TITLE
所有的 ADN-xxx 被识别为 MADN-xxx ，请修复

### ISSUE THREAD

**Issue by siyiye** [Hermit10/AVDCx#42]
bug说明如题

**Comment by Hermit10** [comment]
截图看下哈

**Comment by Hermit10** [comment]
![image](https://user-images.githubusercontent.com/24836174/132851791-4e98de62-2ba3-41c5-985d-abfc92f6c732.png)
复现不了

**Comment by siyiye** [comment]
<?xml version="1.0" encoding="UTF-8" ?>
<movie>
  <num>ADN-018</num>
  <title>ADN-018 孙と行く禁断の温泉旅行 中出し性教育</title>
  <outline>滨崎直子与女儿和孙子三人一起生活着。女儿介绍再婚对象兼温泉旅行，招待滨崎直子与孙子一起出发。然而这两人有着肉体关系…</outline>
  <plot>滨崎直子与女儿和孙子三人一起生活着。女儿介绍再婚对象兼温泉旅行，招待滨崎直子与孙子一起出发。然而这两人有着肉体关系…</plot>
  <set>あなた、許して…。</set>
  <series>あなた、許して…。</series>
  <premiered>2021-03-19</premiered>
  <release>2021-03-19</release>
  <year>2021</year>
  <runtime>104</runtime>
  <rating>4.52</rating>
  <director>なぎら健造</director>
  <studio>ルビー</studio>
  <maker>ルビー</maker>
  <maker>ルビー</maker>
  <cover>https://iqqtv.cloud/preview/80/b/3mgULAdwv3f-800.jpg?v=1617221809</cover>
  <poster>ADN-018-C-poster.jpg</poster>
  <thumb>ADN-018-C-thumb.jpg</thumb>
  <fanart>ADN-018-C-fanart.jpg</fanart>
  <actor>
    <name>浅野多恵子</name>
  </actor>
  <label>
  </label>
  <tag>中出</tag>
  <tag>AV女优片</tag>
  <tag>熟女</tag>
  <tag>温泉</tag>
  <tag>HD高画质</tag>
  <tag>1080P</tag>
  <tag>有码</tag>
  <tag>中文字幕</tag>
  <tag>系列:あなた、許して…。</tag>
  <tag>制作:ルビー</tag>
  <tag>发行:ルビー</tag>
  <genre>中出</genre>
  <genre>AV女优片</genre>
  <genre>熟女</genre>
  <genre>温泉</genre>
  <genre>HD高画质</genre>
  <genre>1080P</genre>
  <genre>有码</genre>
  <genre>中文字幕</genre>
  <genre>系列:あなた、許して…。</genre>
  <genre>制作:ルビー</genre>
  <genre>发行:ルビー</genre>
  <website>https://iqqtv.cloud/cn/player.php?uuid=3mgULAdwv3f</website>
</movie>

**Comment by siyiye** [comment]
look：
![QQ图片20210910225419](https://user-images.githubusercontent.com/35824760/132873633-2732aa0d-85a9-4480-a44e-690dcfac8f4a.png)

**Comment by Hermit10** [comment]
收到!

**Comment by Hermit10** [comment]
已修复，版本20210913
