### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Ozzy-hzy** [Hermit10/AVDCx#43]
## 1.建议将刮削出的图片直接命名为poster.jpg  thumb.jpg  fanart.jpg  
因为有的影片是分段的如SIVR-035-CD1,SIVR-035-CD2,SIVR-035-CD3  这样刮出来有3组图片实际只需要一组，并且影片只要在单独的文件夹，emby刮削出来的图片名字就是默认不带影片名的。

## 3.水印可不可以自定义

**Comment by Ozzy-hzy** [comment]
> 可能每个人的角度不同。
> 1，图片命名目前主要是考虑到：1）视频不在单独文件夹的情况；2）美观性
> 去掉number也可以做，改动的地方还有点多，以后有时间可以加上设置项。
> 2，cd1目前特意改成小写，是为了提高可读性（全是大写感觉是一个灾难。。），或许只能加设置项才能解决
> 3，自定义水印目前支持，在程序目录下，新建Img文件夹，里面放上自定义的水印图片即可。
> 字幕：SUB.png 流出：LEAK.png 无码：UNCENSORED.png

感谢，可能增加设置项就能满足不同人的需求，我目前使用起来就只有这两个痛点，软件已经很完善了

**Comment by Hermit10** [comment]
已增加设置项，版本20210915
