### ISSUE TITLE
感谢作者的奉献，提出两点建议，望采纳

### ISSUE THREAD

**Issue by bohong666** [Hermit10/AVDCx#45]
1、原目录名 例如 070221-001-carib  ，中的 -carib 当前版本会判断成中文。
2、FC2 的文件，经常有分段的视频，除了第一个文件可以刮削移动到成功目录的，其他 同名文件后带-2 ，-3 的文件都不能正确移动到成功目录。

再次感谢作者

**Comment by Hermit10** [comment]
1，收到
2，文件名截图看下

**Comment by bohong666** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hermit10/AVDCx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月14日(星期二) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hermit10/AVDCx] 感谢作者的奉献，提出两点建议，望采纳 (#45)





 
1，收到
 2，文件名截图看下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bohong666** [comment]
![image](https://user-images.githubusercontent.com/86768133/133186284-e5cefe08-f3f0-4440-8b39-ddf3fd523b15.png)
![image](https://user-images.githubusercontent.com/86768133/133186312-6b25bca0-9744-45a9-b8c3-9efb2aa93b14.png)
![image](https://user-images.githubusercontent.com/86768133/133186324-b2d3a63f-fb1c-4542-b8ae-4ff699cfb05f.png)
![image](https://user-images.githubusercontent.com/86768133/133186354-053e98e1-e6f4-45d2-9f6f-7129d1f570c8.png)

**Comment by bohong666** [comment]
FC2-PPV-1837748_2  这个 没有改名的文件是 刮削移动失败的，我刮削后，手动将该文件移动到 刮削正确的目录中的结果

**Comment by Hermit10** [comment]
已更新，版本20210915
