### ISSUE TITLE
与Cloud NAS配合使用时的问题

### ISSUE THREAD

**Issue by liang125448465** [Hermit10/AVDCx#46]
CloudNAS将网盘挂载到本地后，直接削刮网盘中的文件夹时，削刮完成后最后一步删除空文件夹会将整个目录删除。（经测试用cmd命令del也存在一样问题，因此最简单的解决方法是能否开放选项不删除空文件夹。）感谢关注🙏🏻

**Comment by Hermit10** [comment]
好，后面加个设置项。

**Comment by Hermit10** [comment]
已增加设置项，版本20210915
