### ISSUE TITLE
更新后经常发现配置数据丢失的现象

### ISSUE THREAD

**Issue by bohong666** [Hermit10/AVDCx#47]
设置部分都按自己的要求配置好了， 过一段时间，尤其是更新版本后新配置的版本一定会出现一次 配置丢失的现象（设置好的，第二天在打开，发现配置都变成默认值了），需要重新设置。但该现象在一个版本中好像只会出现一次 ！！！

**Comment by bohong666** [comment]
该现象已经持续了很多个版本

**Comment by Hermit10** [comment]
好。我看看

**Comment by Hermit10** [comment]
你的配置能不能发我看下

**Comment by bohong666** [comment]
感谢回复！ 辛苦了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hermit10/AVDCx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 下午4:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hermit10/AVDCx] 更新后经常发现配置数据丢失的现象 (#47)





 
你的配置能不能发我看下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Hermit10** [comment]
我无法重现这个问题。现有逻辑是当配置文件损坏时，才会恢复默认。
1，你是在config.ini里手动修改配置，还是在程序里修改配置？
2，修改了哪些配置？全部都恢复默认了吗？

**Comment by bohong666** [comment]
> 我无法重现这个问题。现有逻辑是当配置文件损坏时，才会恢复默认。
> 1，你是在config.ini里手动修改配置，还是在程序里修改配置？
> 2，修改了哪些配置？全部都恢复默认了吗？

由于版本升级比较频繁，我早起是通过  复制 config 文件来导入配置，然后在程序内做微调的，后来发现有配置文件丢失的现象，所以新版本的配置文件都是 在程序内修改的，主要修改的是文件名规则和代理规则，
如果发生重置配置的现象，那就是全部重置了，和网上下载下来一个状态。

**Comment by Hermit10** [comment]
在程序内修改也会出现配置丢失吗？

**Comment by bohong666** [comment]
会的~

**Comment by Hermit10** [comment]
把你的config上传下

**Comment by bohong666** [comment]
[modified_time]
modified_time = 2021-09-22 16:56:05

[common]
main_mode = 1
no_nfo = 0
main_like = 1
more_website = javdb,jav321
success_file_move = 1
failed_file_move = 0
success_file_rename = 1
del_empty_folder = 1
soft_link = 0
show_poster = 1
translate_language = zh_cn
translate_content = title,outline,actor,tag
translate_by = youdao
deepl_key = 
website = all
series_as_set = 1
# translate_language: zh_cn, zh_tw, ja
# translate_by: youdao, deepl
# website: all, iqqtv, javbus, javdb, jav321, dmm, avsox, xcity, mgstage, fc2, fc2club, fc2hub, airav, javlibrary

[proxy]
type = socks5
proxy = 127.0.0.1:7890
timeout = 10
retry = 3
# type: no, http, socks5

[Cookies]
javdb = theme=auto; locale=zh; over18=1; _ym_d=1631701511; _ym_uid=1631701511241322514; _ym_isad=1; remember_me_token=eyJfcmFpbHMiOnsibWVzc2FnZSI6IkltVnFUamc0UVhwUWVFeGhhME4zZFdacFoydHRJZz09IiwiZXhwIjoiMjAyMS0wOS0yMlQxMDoyNjoyOC4wMDBaIiwicHVyIjoiY29va2llLnJlbWVtYmVyX21lX3Rva2VuIn19--12c0c684839c1a4bbaf4f04066414a24ead35803; _jdb_session=1xUjqI70bF4YcQlLLKdXGTwv2HNsj+EbAv+85c33qeYurm9kQR7tfBYSKZLdCPDnDXdtsSevqtNUhONfMsYQgKatwSlCI8DBo00XWs9b27Sx0bXbNL1hn+UAR751L8ljKWhBvD9nSFaJgHF5JopiwNwtjI+JTQV51HS3QuyO/Pzs1OucG2L4C5Sjeliwzrul9BUdDCyZncx/hoPOXeo4vmBp0e9eWof363h46PaIsEuQcMqSBdcvQj7TYwSlFBcMcG43UjumLsZ2S7xFdjD8dN3sKEfzfJ3W9ewyHt2rrn9T2Gv+NfHE5n8be5PiC92nsv3zqhKiHsfzoV9AqKPoqxVJ--UIHRPz7OBbU2Xj/X--YLIpuvwJdKL4kSg+jLfbPg==
# cookies存在有效期，记得更新

[Name_Rule]
folder_name = number cnword - release - actor - publisher
naming_file = number cnword - release - actor - publisher - definition
naming_media = number cnword - release - actor - publisher - definition
pic_name = 0
cd_name = 1
cnword_char = -C.,中文,字幕
cnword_style = -C
folder_cnword = 0
file_cnword = 0
del_actor_name = 1
# 命名字段有：title, actor, number, studio, publisher, year, mosaic, runtime, director, release, series, definition, cnword

[update]
update_check = 1

[log]
save_log = 0

[media]
media_path = e:\a
success_output_folder = JAV_output
failed_output_folder = failed
extrafanart_folder = 
media_type = .mp4|.avi|.rmvb|.wmv|.mov|.mkv|.flv|.ts|.webm|.iso|.mpg
sub_type = .smi|.srt|.idx|.sub|.sup|.psb|.ssa|.ass|.txt|.usf|.xss|.ssf|.rt|.lrc|.sbv|.vtt|.ttml

[escape]
folders = JAV_output,examples
string = 1080p,720p,22-sht.me,-HD,bbs2048.org@,hhd800.com@,icao.me@,hhb_000
file_size = 100.0

[debug_mode]
switch = 1

[emby]
emby_url = 192.168.5.191:8096
api_key = cb83900340b447fab785cb628a99c3da

[mark]
poster_mark = 1
thumb_mark = 1
mark_size = 5
mark_type = SUB,LEAK,UNCENSORED
mark_pos = top_left
# mark_size: range 1-5
# mark_type: sub, leak, uncensored
# mark_pos: bottom_right, bottom_left, top_right, top_left

[file_download]
old_poster = 0
old_thumb = 0
old_fanart = 0
old_extrafanart = 0
old_extrafanart_copy = 0
old_nfo = 0
poster = 1
thumb = 1
fanart = 1
extrafanart = 0
extrafanart_copy = 0
nfo = 1
poster_source = auto
# poster_source: auto, download

**Comment by bohong666** [comment]
今天早上启动发现 配置又恢复初始化了！

**Comment by bohong666** [comment]
会不会和更新提醒有关系 ，每次出现这个问题都是在新版本发布的这几天内

**Comment by bohong666** [comment]
#
[config.zip](https://github.com/Hermit10/AVDCx/files/7214482/config.zip)

**Comment by Hermit10** [comment]
我用你刚上传的这个CONFIG.ZIP在新版本试了，没有恢复默认。。

**Comment by Hermit10** [comment]
你下载20210924版本，日志页面加了提示，看看报错信息
![image](https://user-images.githubusercontent.com/24836174/134440476-ba4fd015-0f09-419e-a870-cacb4d292395.png)

**Comment by bohong666** [comment]
![image](https://user-images.githubusercontent.com/86768133/134452179-61e5d3a7-b049-4aba-ae72-155573cd3fc2.png)

**Comment by bohong666** [comment]
924版本 默认状态启动 和 软件内修改配置启动后，都显示这个， 没有报错信息。

**Comment by Hermit10** [comment]
> 924版本 默认状态启动 和 软件内修改配置启动后，都显示这个， 没有报错信息。

下次遇到重置问题时，这里会显示报错信息。

**Comment by Hermit10** [comment]
找到一个导致数据恢复的问题：
主界面改变显示封面的开关状态后，点击退出程序，就会重置配置。
该问题已修复，更新20210926
不确定你遇到的是不是这个问题。

**Comment by bohong666** [comment]
我更新试试，我确实有改变封面开关的习惯，前面还真是忽略了这个状态。

**Comment by Hermit10** [comment]
那暂时关闭这个issue，有问题再反馈。
