### ISSUE TITLE
裁剪封面圖的bug

### ISSUE THREAD

**Issue by pixgogo578** [Hermit10/AVDCx#48]
裁剪封面圖時，若資料夾內不只一部影片，會一直覆蓋第一部的封面圖。
ps.手動裁剪

**Comment by Hermit10** [comment]
config上传下

**Comment by pixgogo578** [comment]
[modified_time]
modified_time = 2021-09-17 10:57:59

[common]
main_mode = 1
no_nfo = 0
main_like = 1
more_website = javdb,jav321
success_file_move = 1
failed_file_move = 0
success_file_rename = 1
del_empty_folder = 1
soft_link = 0
show_poster = 1
translate_language = ja
translate_content = title,outline,actor,tag
translate_by = youdao
deepl_key = 
website = all
series_as_set = 1
# translate_language: zh_cn, zh_tw, ja
# translate_by: youdao, deepl
# website: all, iqqtv, javbus, javdb, jav321, dmm, avsox, xcity, mgstage, fc2, fc2club, fc2hub, airav, javlibrary

[proxy]
type = no
proxy = 127.0.0.1:7890
timeout = 10
retry = 3
# type: no, http, socks5

[Cookies]
javdb = 
# cookies存在有效期，记得更新

[Name_Rule]
folder_name = [year]/studio
naming_file = number
naming_media = title
pic_name = 0
cd_name = 0
cnword_char = -C.,中文,字幕
cnword_style = -C
folder_cnword = 0
file_cnword = 1
del_actor_name = 0
# 命名字段有：title, actor, number, studio, publisher, year, mosaic, runtime, director, release, series, definition, cnword

[update]
update_check = 1

[log]
save_log = 1

[media]
media_path = Z:/DL
success_output_folder = JAV_output
failed_output_folder = failed
extrafanart_folder = 
media_type = .mp4|.avi|.rmvb|.wmv|.mov|.mkv|.flv|.ts|.webm|.iso|.mpg
sub_type = .smi|.srt|.idx|.sub|.sup|.psb|.ssa|.ass|.txt|.usf|.xss|.ssf|.rt|.lrc|.sbv|.vtt|.ttml

[escape]
folders = JAV_output,examples
string = 1080p,720p,22-sht.me,-HD,_hd_,_full
file_size = 0.0

[debug_mode]
switch = 1

[emby]
emby_url = 192.168.5.191:8096
api_key = cb83900340b447fab785cb628a99c3da

[mark]
poster_mark = 1
thumb_mark = 0
mark_size = 5
mark_type = SUB,UNCENSORED
mark_pos = top_left
# mark_size: range 1-5
# mark_type: sub, leak, uncensored
# mark_pos: bottom_right, bottom_left, top_right, top_left

[file_download]
old_poster = 0
old_thumb = 0
old_fanart = 0
old_extrafanart = 0
old_extrafanart_copy = 0
old_nfo = 0
poster = 1
thumb = 1
fanart = 1
extrafanart = 0
extrafanart_copy = 0
nfo = 1
poster_source = auto
# poster_source: auto, download

**Comment by pixgogo578** [comment]
另外0915新版本 -1pon 會誤判為 cd1

**Comment by Hermit10** [comment]
已更新，版本20210923
