### ISSUE TITLE
剔除 馬賽克破壞版 的筛选

### ISSUE THREAD

**Issue by happywilly** [Hermit10/AVDCx#49]
RT  有些番号的重命名可能因为某些网站收录了马赛克破坏版的资源 所以命名很奇怪  如果可以的话能不能规避一下？还是说要换源来处理 多谢

[Movie] G:\2\[FHD]PRED-300R.mp4
 🚘 [Number] PRED-300
 🌐 [website] iqqtv[jp] -> javbus -> javdb -> jav321-> airav[ja]
 🟢 Data done!
    title     : 馬賽克破壞版
    actor     : 星奈あい
    outline   : 馬賽克破壞版 PRED-300 星奈あい
    tag       : 無修正,馬賽克破壞版
    release   : 2021-05-25
    year      : 2021
    website   : https://jp.airav.wiki/video/PRED-300?lng=jp
    mosaic    : 有码

**Comment by happywilly** [comment]
ps 再补充一个建议 去掉女优名字的功能挺好的，但是我感觉匹配时 去掉末尾的名字就可以了，否则会有点尴尬  比如：

[FHD]STAR-819 紗倉まな 癒らし。 紗倉まな
[FHD]STAR-819 癒らし。 紗倉まな

**Comment by happywilly** [comment]
ps 再补充一个  iqqtv挂削下来的很多是演员是素人 但是其实在javlibrary里有具体的演员 能否碰到素人演员时直接跳转到javlibrary去挂削~

**Comment by Hermit10** [comment]
> ps 再补充一个建议 去掉女优名字的功能挺好的，但是我感觉匹配时 去掉末尾的名字就可以了，否则会有点尴尬 比如：
> 
> [FHD]STAR-819 紗倉まな 癒らし。 紗倉まな
> [FHD]STAR-819 癒らし。 紗倉まな

这个是哪个刮削网站？

**Comment by happywilly** [comment]
> > ps 再补充一个建议 去掉女优名字的功能挺好的，但是我感觉匹配时 去掉末尾的名字就可以了，否则会有点尴尬 比如：
> > [FHD]STAR-819 紗倉まな 癒らし。 紗倉まな
> > [FHD]STAR-819 癒らし。 紗倉まな
> 
> 这个是哪个刮削网站？

iqqtv应该？  我看了一下最近刮削的文件夹 还是有不少出现这样的情况的 前面的名称里把名字去掉了hhhh

**Comment by Hermit10** [comment]
已更新，版本20210923
