### ISSUE TITLE
分集识别问题

### ISSUE THREAD

**Issue by zuoshandiao-fang** [Hermit10/AVDCx#50]
对于CD1.CD2之类的分集已支持，但对于XXXA和XXXB这类用A.B或者.hd1和.hd2之类的不支持

**Comment by Hermit10** [comment]
提供几个实例看看。

**Comment by Hermit10** [comment]
.hd1和.hd2已支持
.A和.B已支持
更新版本 20210923
xxxa和xxxb请提供实例。

**Comment by zuoshandiao-fang** [comment]
感谢！
