### ISSUE TITLE
建议“字段全”状态下 把javlibrary的优先级提高 图书馆的actor字段好像是最全的

### ISSUE THREAD

**Issue by happywilly** [Hermit10/AVDCx#52]
RT 我开着全局翻墙在 几个网站都能联通 挂削时还是会碰到actor字段 未知演员、素人  等状态  手动去javlibrary发现有演员的名称 
比如

3/6 (50.00%) round(1) [FHD]KRU-072R.mp4
================================================================================
 🙈 [Movie] F:\[1\1\[FHD]KRU-072 素人NTR投稿 親友の彼女を寝取っちゃったヤツ！盗撮して投稿して下さい！ 未知演员\[FHD]KRU-072R.mp4
 🚘 [Number] KRU-072
 🌐 [website] iqqtv[jp] -> javdb -> jav321
 🟢 Data done!
    title     : 素人NTR投稿親友の彼女を寝取っちゃったヤツ！盗撮して投稿して下さい！
    outline   : 俺の彼女は大丈夫だから！！と豪語する親友の彼女さんを寝取ってやった件ww親友を裏切る罪悪感を感じつつ俺の巨根でイク姿がたまらん！一部始終を収録した寝取り映像を勝手にAV発売！
    tag       : 中出,業餘,巨乳,搭訕,寝取り・寝取られ・ntr,1080P
    release   : 2019-12-13
    year      : 2019
    runtime   : 229
    score     : 1.0
    series    : 素人NTR投稿
    publisher : カルマ
    studio    : カルマ
    website   : https://iqqtv.cloud/jp/player.php?uuid=2XH7hTEijcg
    mosaic    : 有码
    c_word    : R
    actor_href: https://javdb.com/search?f=actor&q=
    definition: 1080P
 🟢 Folder done!
 🟢 Thumb done!
 🟢 Poster done!
 🟢 Fanart done!
 🟢 Thumb add watermark: 字幕!
 🟢 Poster add watermark: 字幕!
 🟢 Nfo done!
 🟢 Movie done! 
 🙉 [Movie] F:\[1\1\JAV_output\[FHD]KRU-072 素人NTR投稿親友の彼女を寝取っちゃったヤツ！盗撮して投稿して下さい！ 未知演员\[FHD]KRU-072R.mp4

图书馆里是
<html>
<body>

演员: | 紗凪美羽 阿部栞菜 天月叶菜 なごみ 東山想葉
-- | --

</body>
</html>

**Comment by Hermit10** [comment]
这个还多找一些影片对比。。
字段全只使用了javdb、jav321、dmm（可选）补全，并未使用图书馆。
目前图书馆验证加强了，爬取不了。

**Comment by Hermit10** [comment]
已增加设置项，更新版本20210928
