### ISSUE TITLE
再次出现番号识别错误

### ISSUE THREAD

**Issue by siyiye** [Hermit10/AVDCx#53]
**“th101-140-111881” 被识别为 “th101-140-112594”**

> [Movie] F:\下载\AVDCx-win-20210927\th101-140-111881.MP4
  [Number] 101-140
 [website] iqqtv[jp] -> javbus -> javdb -> jav321
 🟢 Data done!
    title     : ノーパン中出しホームヘルパー
    actor     : 琥珀うた
    tag       : 異物插入,フェラ,自慰,內射,潮吹,無毛,戀物癖,无码,製作：TOKYO-HOT,發行：EMPIRE,1080P
    release   : 2019-04-27
    year      : 2019
    runtime   : 70
    publisher : EMPIRE
    studio    : TOKYO-HOT
    website   : https://www.javbus.com/th101-140-112594
    mosaic    : 无码
    actor_href: https://javdb.com/actors/31Vw
    version   : 20210927
    definition: 1080P
 🟢 Folder done!
 🟢 Thumb done!
 🟢 Poster done!
 🟢 Fanart done!
 🟢 Thumb add watermark: 无码!
 🟢 Poster add watermark: 无码!
 🟢 Nfo done!
 🟢 Movie done! 
  [Movie] F:\下载\AVDCx-win-20210927\JAV_output\琥珀うた\2019-04-27 [th101-140-112594] [未知系列]\th101-140-112594.mp4

**Comment by siyiye** [comment]
另外，mapping_info 文件的391行，应该改为：

  <a zh_cn="玛丹娜" zh_tw="瑪丹娜" jp="Madonna" keyword=",玛丹娜,瑪丹娜,マドンナ,"/>

**Comment by Hermit10** [comment]
收到

**Comment by Hermit10** [comment]
已修复，更新版本0928
